name: x86-64 AppImage

on: [ push, pull_request ]
  branches: [ server-app, add-workflow ]

jobs: 
  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev libfreetype-dev

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      run: cmake --build .

    - name: Build AppImage
      uses: AppImageCrafters/build-appimage-action@add-workflow
      with:
        recipe: dev/AppImageBuilder.yml
      env: 
        UPDATE_INFO: gh-releases-zsync|clasher113|VC_Projector|latest|*x86_64.AppImage.zsync
    - uses: actions/upload-artifact@v4
      with:
        name: AppImage
        path: './*.AppImage*'